// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// cp2015.cpp
cpp4r::sexp solve_model(cpp4r::sexp data, double ufactor, double tol, int maxiter, int triter, bool trace);
extern "C" SEXP _cp2015_solve_model(SEXP data, SEXP ufactor, SEXP tol, SEXP maxiter, SEXP triter, SEXP trace) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(solve_model(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::sexp>>(data), cpp4r::as_cpp<cpp4r::decay_t<double>>(ufactor), cpp4r::as_cpp<cpp4r::decay_t<double>>(tol), cpp4r::as_cpp<cpp4r::decay_t<int>>(maxiter), cpp4r::as_cpp<cpp4r::decay_t<int>>(triter), cpp4r::as_cpp<cpp4r::decay_t<bool>>(trace)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cp2015_solve_model", (DL_FUNC) &_cp2015_solve_model, 6},
    {NULL, NULL, 0}
};
}
extern "C" attribute_visible void R_init_cp2015(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
