# Generated by cpp4r: do not edit by hand

#' @title Solve model
#' @param data a List with the model data.
#' @param ufactor a double with an update factor number between (0, 1]. This value
#'   is used to update the value of variables at each iteration.
#' @param tol a double with the tolerance criteria.
#' @param maxiter an integer with the number of maximum iterations.
#' @param triter an integer indicating that information should be printed for each
#'   multiple of that number.
#' @param trace a boolean indicating whether convergence information should be
#'   printed.
#' @param nthreads an integer indicating the number of threads to use.
#' @export
solve_model <- function(data, ufactor, tol, maxiter, triter, trace, nthreads) {
	.Call(`_cp2015_solve_model`, data, ufactor, tol, maxiter, triter, trace, nthreads)
}
